import { HomeCarCardDetails, ReviewDetails } from './types';

export const carList: HomeCarCardDetails[] = [
  {
    id: '1',
    name: 'Tesla Model 3',
    image: 'https://loremflickr.com/640/480/tesla,car',
    price: 80,
    type: 'automatic',
    fuel_type: 'electric',
    number_of_seats: 5,
    ratings: 4.8,
  },
  {
    id: '2',
    name: 'Toyota Corolla',
    image: 'https://loremflickr.com/640/480/toyota,car',
    price: 50,
    type: 'automatic',
    fuel_type: 'petrol',
    number_of_seats: 5,
    ratings: 4.5,
  },
  {
    id: '3',
    name: 'BMW X5',
    image: 'https://loremflickr.com/640/480/bmw,car',
    price: 90,
    type: 'automatic',
    fuel_type: 'diesel',
    number_of_seats: 5,
    ratings: 4.7,
  },
  {
    id: '4',
    name: 'Ford Mustang',
    image: 'https://loremflickr.com/640/480/ford,mustang',
    price: 95,
    type: 'manual',
    fuel_type: 'petrol',
    number_of_seats: 4,
    ratings: 4.9,
  },
  {
    id: '5',
    name: 'Honda Civic',
    image: 'https://loremflickr.com/640/480/honda,civic',
    price: 55,
    type: 'automatic',
    fuel_type: 'petrol',
    number_of_seats: 5,
    ratings: 4.4,
  },
  {
    id: '6',
    name: 'Audi A6',
    image: 'https://loremflickr.com/640/480/audi,car',
    price: 85,
    type: 'automatic',
    fuel_type: 'hybrid',
    number_of_seats: 5,
    ratings: 4.6,
  },
  {
    id: '7',
    name: 'Jeep Wrangler',
    image: 'https://loremflickr.com/640/480/jeep,wrangler',
    price: 75,
    type: 'manual',
    fuel_type: 'petrol',
    number_of_seats: 4,
    ratings: 4.5,
  },
  {
    id: '8',
    name: 'Mercedes-Benz E-Class',
    image: 'https://loremflickr.com/640/480/mercedes,car',
    price: 100,
    type: 'automatic',
    fuel_type: 'diesel',
    number_of_seats: 5,
    ratings: 4.8,
  },
  {
    id: '9',
    name: 'Hyundai Ioniq 5',
    image: 'https://loremflickr.com/640/480/hyundai,electric',
    price: 65,
    type: 'automatic',
    fuel_type: 'electric',
    number_of_seats: 5,
    ratings: 4.6,
  },
  {
    id: '10',
    name: 'Volkswagen Golf',
    image: 'https://loremflickr.com/640/480/volkswagen,golf',
    price: 60,
    type: 'automatic',
    fuel_type: 'petrol',
    number_of_seats: 5,
    ratings: 4.3,
  },
];


export const reviews: ReviewDetails[] = [
  {
    name: 'Aarav Mehta',
    rating: 5,
    comment: 'Excellent service and great experience!',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    name: 'Ishita Sharma',
    rating: 4,
    comment: 'Very satisfied with the product quality.',
    image: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    name: 'Rohan Deshmukh',
    rating: 3,
    comment: 'It was okay, expected better.',
  },
  {
    name: 'Sanya Kapoor',
    rating: 5,
    comment: 'Loved it! Will recommend to friends.',
    image: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    name: 'Vivaan Iyer',
    rating: 2,
    comment: 'Not up to the mark. Needs improvement.',
  },
  {
    name: 'Ananya Reddy',
    rating: 4,
    comment: 'Really nice experience overall.',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    name: 'Kabir Joshi',
    rating: 5,
    comment: 'Fantastic support team and fast delivery!',
    image: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    name: 'Meera Nair',
    rating: 3,
    comment: 'Decent, but can be better.',
  },
  {
    name: 'Arjun Bhatt',
    rating: 4,
    comment: 'Pretty good experience with quick resolution.',
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    name: 'Diya Chatterjee',
    rating: 5,
    comment: 'Absolutely amazing. Will use again!',
    image: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
];