import { HomeCarCardDetails } from './types';

export const carList: HomeCarCardDetails[] = [
  {
    id: '1',
    name: 'Tesla Model 3',
    image: 'https://loremflickr.com/640/480/tesla,car',
    price: 80,
    type: 'automatic',
    fuel_type: 'electric',
    number_of_seats: 5,
    ratings: 4.8,
  },
  {
    id: '2',
    name: 'Toyota Corolla',
    image: 'https://loremflickr.com/640/480/toyota,car',
    price: 50,
    type: 'automatic',
    fuel_type: 'petrol',
    number_of_seats: 5,
    ratings: 4.5,
  },
  {
    id: '3',
    name: 'BMW X5',
    image: 'https://loremflickr.com/640/480/bmw,car',
    price: 90,
    type: 'automatic',
    fuel_type: 'diesel',
    number_of_seats: 5,
    ratings: 4.7,
  },
  {
    id: '4',
    name: 'Ford Mustang',
    image: 'https://loremflickr.com/640/480/ford,mustang',
    price: 95,
    type: 'manual',
    fuel_type: 'petrol',
    number_of_seats: 4,
    ratings: 4.9,
  },
  {
    id: '5',
    name: 'Honda Civic',
    image: 'https://loremflickr.com/640/480/honda,civic',
    price: 55,
    type: 'automatic',
    fuel_type: 'petrol',
    number_of_seats: 5,
    ratings: 4.4,
  },
  {
    id: '6',
    name: 'Audi A6',
    image: 'https://loremflickr.com/640/480/audi,car',
    price: 85,
    type: 'automatic',
    fuel_type: 'hybrid',
    number_of_seats: 5,
    ratings: 4.6,
  },
  {
    id: '7',
    name: 'Jeep Wrangler',
    image: 'https://loremflickr.com/640/480/jeep,wrangler',
    price: 75,
    type: 'manual',
    fuel_type: 'petrol',
    number_of_seats: 4,
    ratings: 4.5,
  },
  {
    id: '8',
    name: 'Mercedes-Benz E-Class',
    image: 'https://loremflickr.com/640/480/mercedes,car',
    price: 100,
    type: 'automatic',
    fuel_type: 'diesel',
    number_of_seats: 5,
    ratings: 4.8,
  },
  {
    id: '9',
    name: 'Hyundai Ioniq 5',
    image: 'https://loremflickr.com/640/480/hyundai,electric',
    price: 65,
    type: 'automatic',
    fuel_type: 'electric',
    number_of_seats: 5,
    ratings: 4.6,
  },
  {
    id: '10',
    name: 'Volkswagen Golf',
    image: 'https://loremflickr.com/640/480/volkswagen,golf',
    price: 60,
    type: 'automatic',
    fuel_type: 'petrol',
    number_of_seats: 5,
    ratings: 4.3,
  },
];
